= Langchain4j
include::_graphacademy_llm.adoc[]
:slug: langchain4j
:author: Giuseppe Villani
:category: genai-ecosystem
:tags: langchain, langchain4j, java, neo4j, vector, index
:neo4j-versions: 5.x
:page-pagination:
:page-product: langchain4j

image::https://avatars.githubusercontent.com/u/132277850?v=4[width=400]

https://github.com/langchain4j[Langchain4j^] is a Java implementation of the langchain library.
It uses similar concepts, with Prompts, Chains, Transformers, Document Loaders, Agents, and more.

The Neo4j Integration makes the xref:vector-search.adoc[Neo4j Vector] index available in the Langchain4j library.

// https://github.com/langchain4j/langchain4j/tree/main/langchain4j-neo4j

== Installation

.pom.xml
[source,xml]
----
include::https://github.com/langchain4j/langchain4j-examples/raw/main/neo4j-example/pom.xml[lines=19..23]
----

== Functionality Includes

* Create vector index
* Populate nodes and vector index from documents
* Query vector index

== Documentation

An example is avalable at: https://github.com/langchain4j/langchain4j-examples/tree/main/neo4j-example

[source,java]
----
include::https://github.com/langchain4j/langchain4j-examples/raw/main/neo4j-example/src/main/java/Neo4jEmbeddingStoreExample.java[]
----

=== Usage Examples

To add embeddings, execute:
[source,java]
----
Embedding embedding = embeddingModel.embed("embedText").content();
String id = embeddingStore.add(embedding);
// output: id of the embedding
----

To add embeddings with id:
[source,java]
----
String id = randomUUID();
Embedding embedding = embeddingModel.embed("embedText").content();
embeddingStore.add(id, embedding);
// output: id of the embedding
----

To add embeddings with segment:
[source,java]
----
TextSegment segment = TextSegment.from(randomUUID());
Embedding embedding = embeddingModel.embed(segment.text()).content();
String id = embeddingStore.add(embedding, segment);
// output: id of the embedding
----

Too add embeddings with segment and metadata:
[source,java]
----
TextSegment segment = TextSegment.from(randomUUID(), Metadata.from(METADATA_KEY, "test-value"));
Embedding embedding = embeddingModel.embed(segment.text()).content();
String id = embeddingStore.add(embedding, segment);
// output: id of the embedding
----

Search embeddings:
[source,java]
----
Embedding embedding = embeddingModel.embed("embedText").content();
String id = embeddingStore.add(embedding);
final EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
        .queryEmbedding(embedding)
        .maxResults(10)
        .build();
final List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.search(request).matches();
// output: list of embeddings
----

== Relevant Links
[cols="1,4"]
|===
| icon:user[] Authors | https://github.com/vga91[Giuseppe Villani from Neo4j Partner Larus^]
| icon:comments[] Community Support | https://community.neo4j.com/[Neo4j Online Community^]
| icon:github[] Data Repository | https://github.com/langchain4j/langchain4j/[GitHub]
| icon:github[] Issues | https://github.com/langchain4j/langchain4j/issues
// | icon:book[] Documentation |
|===

////

== Videos & Tutorials

Installation:
++++
<iframe width="320" height="180" src="" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

== Highlighted Articles

// link:https://medium.com/neo4j/....[article^]
////
